name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wzhliang/docker-uhttpd/uhttpd:latest
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: wzhliang/docker-uhttpd/uhttpd:latest# optional

